# version: '3.3'

# services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.frontend
  #   ports:
  #     - '3004:3000'
  #   restart: on-failure
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  # backend:
  #   environment:
  #     PORT: 8080
  #     SERVICE_PORT: 5004
  #   container_name: backend
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.backend
  #   ports:
  #     - '5004:8080'
  #   restart: on-failure
  #   volumes:
  #     - .:/usr/src/app


version: '3.3'
services:
  # html:
  #   image: html
  #   environment:
  #     - apiPath=http://api:3333
  #   ports:
  #     - '8080:3334'
  backend:
    image: backend
    environment:
      # PORT: 8080
      SERVICE_PORT: 5004
    ports:
      - '8081:3333'