# Dockerfile.api - for backend project
# Use the official lightweight Node.js 14 image.
FROM node:14-slim
# Create and change to the app directory.
WORKDIR /usr/src/app
# Copy application dependency manifests to the container image.
COPY package*.json ./
COPY yarn.lock ./
# Install dependencies.
RUN yarn
# Copy local code to the container image.
COPY . ./
# Build the app
RUN yarn build:be:prod
# Run the web service on container startup.
CMD ["node", "./dist/apps/backend/main.js"]