version: '3.3'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./apps/frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '3004:3000'
  #   restart: on-failure
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  backend:
    container_name: backend
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    ports:
     - '8081:3333'
    restart: on-failure
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next