version: '3.3'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.frontend
  #   ports:
  #     - '3004:3000'
  #   restart: on-failure
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/.next
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./Dockerfile.backend
    ports:
      - '3434:9090'
    restart: on-failure
    volumes:
      - ./:/app
      - /app/node_modules